### PR TITLE
Feature1

### PR DESCRIPTION
**Pull request by German-Cobian**
This branch contains the clone of the New York Times article

*We used float to position the Editor's Picks as well as for positioning the images and "+" buttons inside the Suggested Newsletters for You boxes
*We used grid to position the "Suggested Newsletters For You", "Most Popular" and "More in Space and Astronomy" sections
*We used flex in the top-nav which contains the social media icons, the bottom links bar and to position the individual items of the "More in Space and Astronomy" section.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello German Cobian Moreno & Miguel Gomez** 
Good job with your first submission for this project :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Add a screenshot in the README file
- [ ] Add the link to the Live Demo in the README file
- [ ] Remove horizontal scrollbar
- [ ] In the CSS file, group selectors with the same style definition
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by German-Cobian** [comment]
Hello Oscar,

Could you please clarify what do you mean by "horizontal scrollbar"? I see the nav-bar at the top and the links nav-bar at the bottom of the page but nothing other than that to, kind-of, fit the definition. Do you mean that we should eliminate "position: fixed" from the top nav-bar?

Thank you,

German



________________________________

**Comment by andresporras3423** [comment]
Hello German,

I mean the horizontal scrollbar that appears because the content exceeds the width of the screen, check out the attached image.

________________________________
De: German-Cobian <notifications@github.com>
Enviado: jueves, 14 de enero de 2021 2:24 p. m.
Para: German-Cobian/Project1-Html-Css <Project1-Html-Css@noreply.github.com>
Cc: Oscar Andrés Russi Porras <oscarrussi@outlook.com>; Mention <mention@noreply.github.com>
Asunto: Re: [German-Cobian/Project1-Html-Css] Feature1 (#1)


Hello Oscar,

Could you please clarify what do you mean by "horizontal scrollbar"? I see the nav-bar at the top and the links nav-bar at the bottom of the page but nothing other than that to, kind-of, fit the definition. Do you mean that we should eliminate "position: fixed" from the top nav-bar?

Thank you,

German



________________________________

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @German-Cobian and @MiguelArgentina :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [ ] Kindly do away with the border around the Editor's pick section.
* [ ] The second image in the Editor's pick section is not displaying. Kindly fix it.

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team. 💻 👀 ✨ 
- Your project seems mostly in order.

## However, there are some changes required 👀 🧰 🔨 🔧 
- As mentioned earlier, your page design overflows to the right in a 100% view of the index page. Please make sure your page fits the screen correctly before re-submitting. Also, there is a broken image on the aside. Please fix this as well.
image
- Remember to add a proper description to your Pull Request as well please. A summary of the concepts you learned and used in this project would be appropriate.
### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by German-Cobian** [comment]
Project1-Html-Css Code Review Improvements

Corrected page so that it does not overflow to the right at a 100% view of the page.
Corrected a broken link that did not permit an image to display on the aside element of the page.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there is one more thing to do. 
### General 
- [ ] Let's  add a proper description to the Pull Request

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @German-Cobian and @MiguelArgentina 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [x] Please remove horizontal scrollbar, as previous TSE suggested. 
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by MiguelArgentina** [comment]
Removed horizontal bar as asked by the TSE's last reviews.

**Review by MiguelArgentina — COMMENTED** [review]
Hello Umair, we have already taken care of the horizontal scrollbar.
Would appreciate your re-review. Thanks

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

**Comment by MiguelArgentina** [comment]
Thanks!

**Pull request merged**
